#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LinearAlgebraSamples
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="LearnerDB")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertQuiz(Quiz instance);
    partial void UpdateQuiz(Quiz instance);
    partial void DeleteQuiz(Quiz instance);
    partial void InsertUser_Test(User_Test instance);
    partial void UpdateUser_Test(User_Test instance);
    partial void DeleteUser_Test(User_Test instance);
    partial void InsertUser_Info(User_Info instance);
    partial void UpdateUser_Info(User_Info instance);
    partial void DeleteUser_Info(User_Info instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["LearnerDBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Quiz> Quizs
		{
			get
			{
				return this.GetTable<Quiz>();
			}
		}
		
		public System.Data.Linq.Table<User_Test> User_Tests
		{
			get
			{
				return this.GetTable<User_Test>();
			}
		}
		
		public System.Data.Linq.Table<User_Info> User_Infos
		{
			get
			{
				return this.GetTable<User_Info>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Quiz")]
	public partial class Quiz : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _Qid;
		
		private string _Question;
		
		private string _optionA;
		
		private string _optionB;
		
		private string _OptionC;
		
		private string _OptionsD;
		
		private string _Answer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnQidChanging(long value);
    partial void OnQidChanged();
    partial void OnQuestionChanging(string value);
    partial void OnQuestionChanged();
    partial void OnoptionAChanging(string value);
    partial void OnoptionAChanged();
    partial void OnoptionBChanging(string value);
    partial void OnoptionBChanged();
    partial void OnOptionCChanging(string value);
    partial void OnOptionCChanged();
    partial void OnOptionsDChanging(string value);
    partial void OnOptionsDChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    #endregion
		
		public Quiz()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qid", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long Qid
		{
			get
			{
				return this._Qid;
			}
			set
			{
				if ((this._Qid != value))
				{
					this.OnQidChanging(value);
					this.SendPropertyChanging();
					this._Qid = value;
					this.SendPropertyChanged("Qid");
					this.OnQidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Question", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Question
		{
			get
			{
				return this._Question;
			}
			set
			{
				if ((this._Question != value))
				{
					this.OnQuestionChanging(value);
					this.SendPropertyChanging();
					this._Question = value;
					this.SendPropertyChanged("Question");
					this.OnQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionA", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string optionA
		{
			get
			{
				return this._optionA;
			}
			set
			{
				if ((this._optionA != value))
				{
					this.OnoptionAChanging(value);
					this.SendPropertyChanging();
					this._optionA = value;
					this.SendPropertyChanged("optionA");
					this.OnoptionAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_optionB", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string optionB
		{
			get
			{
				return this._optionB;
			}
			set
			{
				if ((this._optionB != value))
				{
					this.OnoptionBChanging(value);
					this.SendPropertyChanging();
					this._optionB = value;
					this.SendPropertyChanged("optionB");
					this.OnoptionBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionC", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string OptionC
		{
			get
			{
				return this._OptionC;
			}
			set
			{
				if ((this._OptionC != value))
				{
					this.OnOptionCChanging(value);
					this.SendPropertyChanging();
					this._OptionC = value;
					this.SendPropertyChanged("OptionC");
					this.OnOptionCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OptionsD", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string OptionsD
		{
			get
			{
				return this._OptionsD;
			}
			set
			{
				if ((this._OptionsD != value))
				{
					this.OnOptionsDChanging(value);
					this.SendPropertyChanging();
					this._OptionsD = value;
					this.SendPropertyChanged("OptionsD");
					this.OnOptionsDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Test")]
	public partial class User_Test : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _TestNo;
		
		private int _UidNo;
		
		private int _Score;
		
		private System.DateTime _Test_Date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTestNoChanging(long value);
    partial void OnTestNoChanged();
    partial void OnUidNoChanging(int value);
    partial void OnUidNoChanged();
    partial void OnScoreChanging(int value);
    partial void OnScoreChanged();
    partial void OnTest_DateChanging(System.DateTime value);
    partial void OnTest_DateChanged();
    #endregion
		
		public User_Test()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TestNo", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long TestNo
		{
			get
			{
				return this._TestNo;
			}
			set
			{
				if ((this._TestNo != value))
				{
					this.OnTestNoChanging(value);
					this.SendPropertyChanging();
					this._TestNo = value;
					this.SendPropertyChanged("TestNo");
					this.OnTestNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UidNo", DbType="Int NOT NULL")]
		public int UidNo
		{
			get
			{
				return this._UidNo;
			}
			set
			{
				if ((this._UidNo != value))
				{
					this.OnUidNoChanging(value);
					this.SendPropertyChanging();
					this._UidNo = value;
					this.SendPropertyChanged("UidNo");
					this.OnUidNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Score", DbType="Int NOT NULL")]
		public int Score
		{
			get
			{
				return this._Score;
			}
			set
			{
				if ((this._Score != value))
				{
					this.OnScoreChanging(value);
					this.SendPropertyChanging();
					this._Score = value;
					this.SendPropertyChanged("Score");
					this.OnScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Test_Date", DbType="DateTime NOT NULL")]
		public System.DateTime Test_Date
		{
			get
			{
				return this._Test_Date;
			}
			set
			{
				if ((this._Test_Date != value))
				{
					this.OnTest_DateChanging(value);
					this.SendPropertyChanging();
					this._Test_Date = value;
					this.SendPropertyChanged("Test_Date");
					this.OnTest_DateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Info")]
	public partial class User_Info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UidNo;
		
		private string _First_name;
		
		private string _Last_name;
		
		private string _Mobile_number;
		
		private string _E_mail_id;
		
		private System.DateTime _DOB;
		
		private string _Address_Communication;
		
		private string _Usr_pwd;
		
		private string _Usr_type;
		
		private string _Gender;
		
		private System.Nullable<bool> _Isactive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUidNoChanging(int value);
    partial void OnUidNoChanged();
    partial void OnFirst_nameChanging(string value);
    partial void OnFirst_nameChanged();
    partial void OnLast_nameChanging(string value);
    partial void OnLast_nameChanged();
    partial void OnMobile_numberChanging(string value);
    partial void OnMobile_numberChanged();
    partial void OnE_mail_idChanging(string value);
    partial void OnE_mail_idChanged();
    partial void OnDOBChanging(System.DateTime value);
    partial void OnDOBChanged();
    partial void OnAddress_CommunicationChanging(string value);
    partial void OnAddress_CommunicationChanged();
    partial void OnUsr_pwdChanging(string value);
    partial void OnUsr_pwdChanged();
    partial void OnUsr_typeChanging(string value);
    partial void OnUsr_typeChanged();
    partial void OnGenderChanging(string value);
    partial void OnGenderChanged();
    partial void OnIsactiveChanging(System.Nullable<bool> value);
    partial void OnIsactiveChanged();
    #endregion
		
		public User_Info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UidNo", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int UidNo
		{
			get
			{
				return this._UidNo;
			}
			set
			{
				if ((this._UidNo != value))
				{
					this.OnUidNoChanging(value);
					this.SendPropertyChanging();
					this._UidNo = value;
					this.SendPropertyChanged("UidNo");
					this.OnUidNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_First_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string First_name
		{
			get
			{
				return this._First_name;
			}
			set
			{
				if ((this._First_name != value))
				{
					this.OnFirst_nameChanging(value);
					this.SendPropertyChanging();
					this._First_name = value;
					this.SendPropertyChanged("First_name");
					this.OnFirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Last_name", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Last_name
		{
			get
			{
				return this._Last_name;
			}
			set
			{
				if ((this._Last_name != value))
				{
					this.OnLast_nameChanging(value);
					this.SendPropertyChanging();
					this._Last_name = value;
					this.SendPropertyChanged("Last_name");
					this.OnLast_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mobile_number", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Mobile_number
		{
			get
			{
				return this._Mobile_number;
			}
			set
			{
				if ((this._Mobile_number != value))
				{
					this.OnMobile_numberChanging(value);
					this.SendPropertyChanging();
					this._Mobile_number = value;
					this.SendPropertyChanged("Mobile_number");
					this.OnMobile_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[E-mail_id]", Storage="_E_mail_id", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string E_mail_id
		{
			get
			{
				return this._E_mail_id;
			}
			set
			{
				if ((this._E_mail_id != value))
				{
					this.OnE_mail_idChanging(value);
					this.SendPropertyChanging();
					this._E_mail_id = value;
					this.SendPropertyChanged("E_mail_id");
					this.OnE_mail_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOB", DbType="DateTime NOT NULL")]
		public System.DateTime DOB
		{
			get
			{
				return this._DOB;
			}
			set
			{
				if ((this._DOB != value))
				{
					this.OnDOBChanging(value);
					this.SendPropertyChanging();
					this._DOB = value;
					this.SendPropertyChanged("DOB");
					this.OnDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address_Communication", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Address_Communication
		{
			get
			{
				return this._Address_Communication;
			}
			set
			{
				if ((this._Address_Communication != value))
				{
					this.OnAddress_CommunicationChanging(value);
					this.SendPropertyChanging();
					this._Address_Communication = value;
					this.SendPropertyChanged("Address_Communication");
					this.OnAddress_CommunicationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr_pwd", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Usr_pwd
		{
			get
			{
				return this._Usr_pwd;
			}
			set
			{
				if ((this._Usr_pwd != value))
				{
					this.OnUsr_pwdChanging(value);
					this.SendPropertyChanging();
					this._Usr_pwd = value;
					this.SendPropertyChanged("Usr_pwd");
					this.OnUsr_pwdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usr_type", DbType="VarChar(100)")]
		public string Usr_type
		{
			get
			{
				return this._Usr_type;
			}
			set
			{
				if ((this._Usr_type != value))
				{
					this.OnUsr_typeChanging(value);
					this.SendPropertyChanging();
					this._Usr_type = value;
					this.SendPropertyChanged("Usr_type");
					this.OnUsr_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="VarChar(200)")]
		public string Gender
		{
			get
			{
				return this._Gender;
			}
			set
			{
				if ((this._Gender != value))
				{
					this.OnGenderChanging(value);
					this.SendPropertyChanging();
					this._Gender = value;
					this.SendPropertyChanged("Gender");
					this.OnGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isactive", DbType="Bit")]
		public System.Nullable<bool> Isactive
		{
			get
			{
				return this._Isactive;
			}
			set
			{
				if ((this._Isactive != value))
				{
					this.OnIsactiveChanging(value);
					this.SendPropertyChanging();
					this._Isactive = value;
					this.SendPropertyChanged("Isactive");
					this.OnIsactiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
